### ISSUE TITLE
Removing and readding the powercell card to a full dimensional cell causes infinte power

### ISSUE THREAD

**Issue by emilianya** [McJtyMods/RFToolsPower#78] opened 2022-01-18 17:46 UTC
Game version 1.18

Steps to reproduce:
Full dimensional cell, linked to another dimensional cell via powercell cards
Remove the powercell cards, and add it back, the power in the dimensional cell gets added to the total, and you now have more power than you started with.
![image](https://user-images.githubusercontent.com/47392011/149990856-57cf2764-cdf6-4dc8-8fd6-6fe4249cbb92.png)

**Comment by McJty** [comment] 2022-01-19 13:48
Hmm. I cannot reproduce this. When I break the dimensional cell and put it back the end resut is the same. I need more details

**Comment by emilianya** [comment] 2022-01-19 17:45
> Hmm. I cannot reproduce this. When I break the dimensional cell and put it back the end resut is the same. I need more details

I seem to have had a brain fart while writing that, I didnt mean breaking the cell, i meant removing and readding the powercell card, edited the issue to reflect that
Will make a video to demonstrate it

**Comment by emilianya** [comment] 2022-01-19 17:58
https://user-images.githubusercontent.com/47392011/150187333-f18dfb3a-52cf-42f6-9db6-1079fc34fa64.mp4

**Comment by McJty** [comment] 2022-01-19 18:14
Hmm. Can't reproduce that either. There are some bugs though but none that give me infinite power. I'll fix the other bugs that I found

**Comment by McJty** [comment] 2022-05-08 14:01
Fixed in the latest version

**Closed as completed by McJty** 2022-05-08 14:01 UTC
