### ISSUE TITLE
[1.14.4] Coal generator missing textures

### ISSUE THREAD

**Issue by ScrambledGamer** [McJtyMods/RFToolsPower#25] opened 2019-08-14 21:24 UTC
Coal generator missing texture on all sides besides front when not active and front also missing when active

**Comment by McJty** [comment] 2019-08-15 04:42
More information please! Versions of the mod, forge, ...

**Comment by ProsperCraft** [comment] 2019-08-15 04:54
Duplicate of - https://github.com/McJtyMods/RFToolsPower/issues/24

**Comment by McJty** [comment] 2019-10-15 11:56
Can't reproduce

**Comment by ProsperCraft** [comment] 2019-10-15 13:05
I resolved this in https://github.com/McJtyMods/RFToolsPower/issues/24 you can close.

**Closed as completed** 2019-10-15 13:08 UTC
